name: 'fitness_dash_dbt'
version: '1.0.0'

profile: 'fitness_dash_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  fitness_dash_dbt:

    staging:
      +schema: silver
      +materialized: incremental
      +tags: ["silver"]

    marts:
      +schema: gold
      +materialized: table
      +tags: ["gold"]