services:
  postgres:
    image: postgres:17
    container_name: fitness-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbt:
    build:
      context: ../fitness_dash_dbt
    container_name: fitness-dbt
    restart: "no"

    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - ../fitness_dash_dbt:/app

    working_dir: /app

    depends_on:
      - postgres

    command: ["dbt", "--version"]

  metabase:
    image: metabase/metabase:latest
    container_name: fitness-metabase
    restart: unless-stopped

    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_METABASE_USER}
      MB_DB_PASS: ${POSTGRES_METABASE_PASSWORD}
      MB_DB_HOST: postgres

      JAVA_TIMEZONE: Europe/Warsaw

    ports:
      - "${METABASE_PORT}:3000"

    depends_on:
      - postgres

volumes:
  postgres_data:
